# Generated by Django 4.0 on 2022-01-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('trend', models.CharField(choices=[('U', 'Upward'), ('D', 'Downward'), ('S', 'Side Wise')], max_length=30, verbose_name='Trend')),
                ('todays_high', models.IntegerField(blank=True, verbose_name="Today's High")),
                ('todays_low', models.IntegerField(blank=True, verbose_name="Today's Low")),
                ('support', models.IntegerField(blank=True, verbose_name='Support')),
                ('resistance', models.IntegerField(blank=True, verbose_name='Resistance')),
                ('percentage', models.IntegerField(blank=True, verbose_name='Chance Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(blank=True, verbose_name='Target Amount')),
                ('trades_required', models.IntegerField(blank=True, default=10, verbose_name='Number Of Trades')),
                ('target_accured', models.BooleanField(default=False)),
                ('diffrence', models.IntegerField(blank=True, verbose_name='Diffrence From Target')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField(blank=True, verbose_name='Buy Price')),
                ('sale', models.IntegerField(blank=True, verbose_name='Sale Price')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('P', 'Profit'), ('L', 'Loss'), ('N', 'NO Change')], max_length=30, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_info.today')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_info.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Mnt', 'Minitue'), ('Hr', 'Hour'), ('Day', 'Day'), ('Wk', 'Week'), ('Mnth', 'Month')], max_length=30, verbose_name='Period')),
                ('open_price', models.IntegerField(blank=True, verbose_name='Open Price')),
                ('close_price', models.IntegerField(blank=True, verbose_name='Close Price')),
                ('high_price', models.IntegerField(blank=True, verbose_name='High Price')),
                ('low_price', models.IntegerField(blank=True, verbose_name='High Price')),
                ('volume', models.IntegerField(blank=True, verbose_name='Voulume')),
                ('change_rate', models.IntegerField(blank=True, verbose_name='Rate Of Change')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_info.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='Price')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_info.stock')),
            ],
        ),
    ]
