# Generated by Django 4.0 on 2022-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0003_myprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
        migrations.AddField(
            model_name='stock',
            name='change_rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rate Of Change'),
            preserve_default=False,
        ),
    ]
