# Generated by Django 4.0 on 2022-01-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0004_rename_trades_trade_stock_change_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trend',
            field=models.CharField(blank=True, choices=[('U', 'Upward'), ('D', 'Downward'), ('S', 'Side Wise')], max_length=30, verbose_name='Trend'),
        ),
    ]
