# Generated by Django 4.0 on 2022-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0005_alter_stock_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rate Of Change'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chance Percentage'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='resistance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resistance'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='support',
            field=models.IntegerField(blank=True, null=True, verbose_name='Support'),
        ),
    ]
