# Generated by Django 4.0 on 2022-01-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0007_alter_currentprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='gain_margin',
            field=models.FloatField(blank=True, verbose_name='Margin'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='loss',
            field=models.FloatField(blank=True, verbose_name='Total Loss'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='profit',
            field=models.FloatField(blank=True, verbose_name='Total Profit'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='target_percentage',
            field=models.FloatField(blank=True, verbose_name='Target Percentage'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='wallet',
            field=models.FloatField(blank=True, verbose_name='Wallet Balance'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='change_rate',
            field=models.FloatField(blank=True, verbose_name='Rate Of Change'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='close_price',
            field=models.FloatField(blank=True, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='high_price',
            field=models.FloatField(blank=True, verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='low_price',
            field=models.FloatField(blank=True, verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='open_price',
            field=models.FloatField(blank=True, verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate Of Change'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Chance Percentage'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='resistance',
            field=models.FloatField(blank=True, null=True, verbose_name='Resistance'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='support',
            field=models.FloatField(blank=True, null=True, verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='todays_high',
            field=models.FloatField(blank=True, verbose_name="Today's High"),
        ),
        migrations.AlterField(
            model_name='stock',
            name='todays_low',
            field=models.FloatField(blank=True, verbose_name="Today's Low"),
        ),
        migrations.AlterField(
            model_name='today',
            name='diffrence',
            field=models.FloatField(blank=True, verbose_name='Diffrence From Target'),
        ),
        migrations.AlterField(
            model_name='today',
            name='target',
            field=models.FloatField(blank=True, verbose_name='Target Amount'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy',
            field=models.FloatField(blank=True, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sale',
            field=models.FloatField(blank=True, verbose_name='Sale Price'),
        ),
    ]
