# Generated by Django 4.0 on 2022-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0008_alter_myprofile_gain_margin_alter_myprofile_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Close Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Open Price'),
            preserve_default=False,
        ),
    ]
