# Generated by Django 4.0 on 2022-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0009_stock_close_price_stock_open_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voulume'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Open Price'),
        ),
    ]
