# Generated by Django 4.0 on 2022-01-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0010_stock_volume_alter_stock_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='Voulume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='stock_info.stock'),
        ),
    ]
