# Generated by Django 4.0 on 2022-01-12 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0011_currentprice_volume_alter_currentprice_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
    ]
