# Generated by Django 4.0 on 2022-01-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0012_currentprice_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='percentage',
        ),
        migrations.AddField(
            model_name='stock',
            name='buy_chance',
            field=models.FloatField(blank=True, null=True, verbose_name='Chance Buy'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sell_chance',
            field=models.FloatField(blank=True, null=True, verbose_name='Chance Sell'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='low_price',
            field=models.FloatField(blank=True, verbose_name='Low Price'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='volume',
            field=models.IntegerField(blank=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Voulume'),
        ),
    ]
