# Generated by Django 4.0 on 2022-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0013_remove_stock_percentage_stock_buy_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Volume'),
        ),
    ]
