# Generated by Django 4.0 on 2022-01-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0014_stock_price_alter_stock_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='today',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capital'),
        ),
        migrations.AddField(
            model_name='trade',
            name='revenue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Profit'), ('L', 'Loss'), ('N', 'NO Change')], max_length=30, verbose_name='Status'),
        ),
    ]
