# Generated by Django 4.0 on 2022-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0015_today_capital_trade_revenue_alter_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='diffrence',
            field=models.FloatField(blank=True, null=True, verbose_name='Diffrence From Target'),
        ),
        migrations.AlterField(
            model_name='today',
            name='target',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Amount'),
        ),
    ]
