# Generated by Django 4.0 on 2022-01-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0019_alter_trade_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_info.today'),
        ),
    ]
