# Generated by Django 4.0 on 2022-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0020_alter_trade_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='revenue',
            field=models.FloatField(blank=True, null=True, verbose_name='Revenue'),
        ),
    ]
