# Generated by Django 4.0 on 2022-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0021_alter_trade_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
