# Generated by Django 4.0 on 2022-01-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0022_alter_today_created_time_alter_trade_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='day',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='stock_info.today'),
            preserve_default=False,
        ),
    ]
